name: Test - Terraform test action
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - '*'         # matches every branch that doesn't contain a '/'
      - '*/*'       # matches every branch containing a single '/'
      - '**'        # matches every branch
    paths:
      - '**.tf'
      - '**.tfvars'
      - '**.rb'
      - '.github/workflows/terraform.yml'

#Ensures that only one terraform task run at a time.
concurrency:
  group: terraform

jobs:
  test:
    name: Terraform Tests
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Get APP token
        id: otc-tests
        uses: peter-murray/workflow-application-token-action@v2
        with:
          application_id: ${{ secrets.APP_ID }}
          application_private_key: ${{ secrets.APP_PRIVATE_KEY }}

      - uses: actions/checkout@v3
        with:
          token: ${{ steps.otc-tests.outputs.token }}

      - id: root_test
        name: Test - Root Module
        uses: Ontracon/otc-test-terraform-action@main
        with:
          ROOT_DIR: '${{ github.workspace }}/'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ROOT_MODULE: 'true'
          PUBLISH_NAME: 'Results - root'

      - id: aws_test_10_example
        name: 'AWS Example 10-simple' 
        uses: Ontracon/otc-test-terraform-action@main
        with:
          ROOT_DIR: '${{ github.workspace }}/examples/10-simple'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
          CLOUD_REGION: 'eu-central-1'
          AUTO_CREATE_TF_BACKEND: 'true'
          AWS_ACCESS_KEY_ID: ${{ secrets.OTC_TEST_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.OTC_TEST_AWS_SECRET_ACCESS_KEY }}
          PUBLISH_NAME: 'Results - AWS Example 10-simple'      
      # 
      # - id: azure_test
      #   name: Test - Azure
      #   uses: ./
      #   with:
      #     ROOT_DIR: '${{ github.workspace }}/tests/azure'
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     CLOUD_REGION: 'westeurope'
      #     AUTO_CREATE_TF_BACKEND: 'true'
      #     ARM_CLIENT_ID: ${{ secrets.OTC_TEST_ARM_CLIENT_ID }}
      #     ARM_CLIENT_SECRET: ${{ secrets.OTC_TEST_ARM_CLIENT_SECRET }}
      #     ARM_TENANT_ID: ${{ secrets.OTC_TEST_ARM_TENANT_ID }}
      #     ARM_SUBSCRIPTION_ID: ${{ secrets.OTC_TEST_ARM_SUBSCRIPTION_ID }}
      #     PUBLISH_NAME: 'Results - Azure'      
